export const Houses = [
  {
    img: "/Houses/Apartament1.jpg",
    title: "New Apartment at downtown",
    location: "ZURICH",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 4,
    bath: 2,
    meter: 100,
    price: 400000,
    long: 8.5,
    lat: 47.37974518618849,
    type: "Apartment",
  },

  {
    img: "/Houses/Attico.jpg",
    location: "LUGANO",
    title: "New Loft in Lugano",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 4,
    bath: 2,
    meter: 200,
    price: 450000,
    long: 8.956807,
    lat: 46.00992,
    type: "Loft",
  },
  {
    img: "/Houses/Apartament.jpg",
    location: "LUGANO",
    title: "Nice Apartment with lake view",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 2,
    bath: 1,
    meter: 67,
    price: 530000,
    long: 8.9501,
    lat: 46.007,
    type: "Apartment",
  },
  {
    img: "/Houses/Villa5.jpg",
    location: "ZUG",
    title: "Fantastic Villa with swimming pool",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 6,
    bath: 3,
    meter: 94,
    price: 900000,
    long: 8.498,
    lat: 47.182,
    type: "Villa",
  },
  {
    img: "/Houses/Attico2.jpg",
    location: "LOCARNO",
    title: "New Loft in Locarno",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 2,
    bath: 1,
    meter: 70,
    price: 300000,
    long: 8.798,
    lat: 46.162,
    type: "Loft",
  },
  {
    img: "/Houses/Villa.jpg",
    location: "GENEVA",
    title: "Luxury Villa in Geneva, with a big pool and gym",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 6,
    bath: 3,
    meter: 100,

    price: 900000,
    long: 6.14,
    lat: 46.218,
    type: "Villa",
  },
  {
    img: "/Houses/Apartament3.jpg",
    location: "BASEL",
    title: "New Apartment at downtown",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 4,
    bath: 2,
    meter: 100,
    price: 600000,
    long: 7.582044,
    lat: 47.5686,
    type: "Apartment",
  },
  {
    img: "/Houses/Apartament2.jpg",
    location: "BERN",
    title: "Nice Apartment near to the public transport",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 2,
    bath: 1,
    meter: 50,
    price: 500000,
    long: 7.4656,
    lat: 46.94616,
    type: "Apartment",
  },

  {
    img: "/Houses/Villa2.jpg",
    location: "LUCERNE",
    title: "Big Villa",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 5,
    bath: 3,
    meter: 140,
    price: 1000000,
    long: 8.31044,
    lat: 47.05686,
    type: "Villa",
  },

  {
    img: "/Houses/Attico2.jpg",
    location: "ST. GALLEN",
    title: "Small Loft",
    description:
      "This Spectacular Home  is not only an oasis for your eyes, but has been fully upgraded to welcome you home. A private long driveway leads you to the front of the home with a 2 car garage",
    rooms: 2,
    bath: 1,
    meter: 62,
    price: 320000,
    long: 9.35114,
    lat: 47.420506,
    type: "Loft",
  },
];
